// Generated by Drop. You probably shouldn't modify this file, your computer might explode!
// Timestamp: {{ timestamp }}

#include <stddef.h>

#include "drop.h"

{% for include in includes %}
{{ include }}
{% endfor %}

const struct drop_meta_type_s float_meta = {
    .name = "float"
};

const struct drop_meta_type_s int_meta = {
    .name = "int"
};

const struct drop_meta_type_s uint32_t_meta = {
    .name = "uint32_t"
};

const struct drop_meta_type_s bool_meta = {
    .name = "bool"
};

const struct drop_meta_type_s char_meta = {
    .name = "char"
};

const struct drop_meta_type_s size_t_meta = {
    .name = "uint32_t"
};;

const struct drop_meta_type_s rain_asset_type_meta = {
    .name = "uint32_t"
};;

{% for struct in structs %}
// Drop-generated meta definition for {{ struct.name }}.
{% include 'struct.c' %}
{% endfor %}
